#!/usr/bin/env python3
"""Acquire and verify the exact VPO bytes used by the comparative study.

The lock generated by this program deliberately defines equivalence at the
analysis-input boundary: every selected GrandOrgue definition and every unique
audio file that contributed an observation must be present with its frozen
SHA-256. It does not claim byte equivalence for files that were never analyzed
or for the former 591 GB discovery collection as a whole.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
import zipfile
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


LOCK_CONTRACT = "orgrec-vpo-analysis-acquisition-lock/1"
VERIFY_CONTRACT = "orgrec-vpo-analysis-acquisition-verification/1"
AUDIT_CONTRACT = "orgrec-vpo-source-route-audit/1"
INVENTORY_REMAP_CONTRACT = "orgrec-vpo-inventory-remap/1"
CORPUS_COMPARISON_CONTRACT = "orgrec-vpo-feature-corpus-comparison/1"
RESULT_COMPARISON_CONTRACT = "orgrec-vpo-result-comparison/1"
USER_AGENT = "OrgRec-VPO-Reproducer/1"
AUDIO_EXTENSIONS = {".wav", ".wave", ".flac", ".aif", ".aiff"}
DEFINITION_EXTENSIONS = {".organ"}
HASH_EXTENSIONS = AUDIO_EXTENSIONS | DEFINITION_EXTENSIONS


class ReproductionError(RuntimeError):
    pass


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def sha256_file(path: Path, chunk_size: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while chunk := handle.read(chunk_size):
            digest.update(chunk)
    return digest.hexdigest()


def sha256_stream(handle: Any, chunk_size: int = 8 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    while chunk := handle.read(chunk_size):
        digest.update(chunk)
    return digest.hexdigest()


def canonical_json_hash(value: Any) -> str:
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    with temporary.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, ensure_ascii=False, indent=2, sort_keys=True)
        handle.write("\n")
    os.replace(temporary, path)


def parse_root_maps(values: list[str]) -> list[tuple[str, str]]:
    mappings: list[tuple[str, str]] = []
    for value in values:
        if "=" not in value:
            raise ReproductionError(f"Invalid --root-map value: {value}")
        old, new = value.split("=", 1)
        old = old.rstrip("/")
        new = new.rstrip("/")
        if not old or not new:
            raise ReproductionError(f"Invalid --root-map value: {value}")
        mappings.append((old, new))
    old_roots = [old for old, _ in mappings]
    if len(set(old_roots)) != len(old_roots):
        raise ReproductionError("Duplicate old root in --root-map values")
    return sorted(mappings, key=lambda item: len(item[0]), reverse=True)


def remap_path(value: str, mappings: list[tuple[str, str]]) -> tuple[str, bool]:
    for old, new in mappings:
        if value == old or value.startswith(old + "/"):
            return new + value[len(old):], True
    return value, False


def remap_inventory(
    inventory_path: Path,
    output_path: Path,
    mappings: list[tuple[str, str]],
) -> dict[str, Any]:
    with inventory_path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        fieldnames = reader.fieldnames
        if not fieldnames or "path" not in fieldnames:
            raise ReproductionError("Inventory has no path column")
        rows = list(reader)
    remapped_rows = 0
    mapped_missing: list[dict[str, str]] = []
    current_existing = 0
    for row in rows:
        was_expected_present = row.get("path_exists", "").lower() == "yes"
        new_path, changed = remap_path(row.get("path", ""), mappings)
        row["path"] = new_path
        if changed:
            remapped_rows += 1
        exists = bool(new_path) and Path(new_path).exists()
        if "path_exists" in row:
            row["path_exists"] = "yes" if exists else "no"
        if exists:
            current_existing += 1
        elif changed and was_expected_present:
            mapped_missing.append({"entityID": row.get("entity_id", ""), "path": new_path})
        if "manifest_path" in row:
            row["manifest_path"], _ = remap_path(row.get("manifest_path", ""), mappings)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(output_path.name + ".tmp")
    with temporary.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    os.replace(temporary, output_path)
    return {
        "contractVersion": INVENTORY_REMAP_CONTRACT,
        "generatedAt": utc_now(),
        "sourceInventory": str(inventory_path.resolve()),
        "sourceInventorySHA256": sha256_file(inventory_path),
        "outputInventory": str(output_path.resolve()),
        "outputInventorySHA256": sha256_file(output_path),
        "rootMappings": [{"old": old, "new": new} for old, new in mappings],
        "summary": {
            "rowCount": len(rows),
            "remappedRowCount": remapped_rows,
            "currentExistingPathCount": current_existing,
            "historicallyExpectedPresentMissingPathCount": len(mapped_missing),
        },
        "historicallyExpectedPresentMissingPaths": mapped_missing,
    }


def scientific_corpus_payload(document: dict[str, Any]) -> dict[str, Any]:
    """Return the scientific payload, excluding machine/run provenance paths."""
    instruments = []
    for source in document.get("instruments", []):
        item = dict(source)
        item.pop("sourceDefinitionPath", None)
        instruments.append(item)
    ranks = json.loads(json.dumps(document.get("ranks", [])))
    for rank in ranks:
        for observation in rank.get("observations", []):
            observation.pop("id", None)
    return {
        "contractVersion": document.get("contractVersion"),
        "sourceMutationPolicy": document.get("sourceMutationPolicy"),
        "options": document.get("options"),
        "catalogSHA256": document.get("catalogSHA256"),
        "instruments": instruments,
        "ranks": ranks,
        "exclusions": document.get("exclusions", []),
        "warnings": document.get("warnings", []),
    }


def compare_corpora(reference_path: Path, candidate_path: Path) -> dict[str, Any]:
    reference = scientific_corpus_payload(load_json(reference_path))
    candidate = scientific_corpus_payload(load_json(candidate_path))
    sections = {}
    for key in reference:
        sections[key] = {
            "equivalent": reference.get(key) == candidate.get(key),
            "referenceSHA256": canonical_json_hash(reference.get(key)),
            "candidateSHA256": canonical_json_hash(candidate.get(key)),
        }
    equivalent = reference == candidate
    return {
        "contractVersion": CORPUS_COMPARISON_CONTRACT,
        "generatedAt": utc_now(),
        "status": "feature-corpus equivalent" if equivalent else "corpus variant",
        "equivalent": equivalent,
        "comparisonBoundary": "Scientific corpus content; generated time, software build metadata, inventory path/hash, catalog path, source-definition filesystem paths, and randomly generated observation record UUIDs are excluded.",
        "reference": str(reference_path.resolve()),
        "candidate": str(candidate_path.resolve()),
        "referencePayloadSHA256": canonical_json_hash(reference),
        "candidatePayloadSHA256": canonical_json_hash(candidate),
        "sections": sections,
    }


RESULT_JSON_FILES = ("summary.json",)
RESULT_CSV_FILES = (
    "analysis-exclusions.csv",
    "association-tests.csv",
    "classification-predictions-all_rank_features.csv",
    "classification-predictions-primary_endpoints.csv",
    "classification-summary.csv",
    "pca-loadings.csv",
    "pca-scores.csv",
    "stop-name-summary.csv",
)


def canonical_csv(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        return {"fieldnames": reader.fieldnames, "rows": list(reader)}


def compare_results(reference_dir: Path, candidate_dir: Path) -> dict[str, Any]:
    files = []
    for filename in RESULT_JSON_FILES + RESULT_CSV_FILES:
        reference_path = reference_dir / filename
        candidate_path = candidate_dir / filename
        if not reference_path.is_file() or not candidate_path.is_file():
            files.append({
                "file": filename,
                "equivalent": False,
                "error": "missing reference or candidate file",
            })
            continue
        if filename.endswith(".json"):
            reference = load_json(reference_path)
            candidate = load_json(candidate_path)
        else:
            reference = canonical_csv(reference_path)
            candidate = canonical_csv(candidate_path)
        files.append({
            "file": filename,
            "equivalent": reference == candidate,
            "referenceCanonicalSHA256": canonical_json_hash(reference),
            "candidateCanonicalSHA256": canonical_json_hash(candidate),
        })
    equivalent = all(item["equivalent"] for item in files)
    return {
        "contractVersion": RESULT_COMPARISON_CONTRACT,
        "generatedAt": utc_now(),
        "status": "scientific results equivalent" if equivalent else "result variant",
        "equivalent": equivalent,
        "comparisonBoundary": "Exact canonical comparison of the statistical summary and all analysis CSV tables; run-provenance timestamps/paths and renderer-dependent figures are excluded.",
        "reference": str(reference_dir.resolve()),
        "candidate": str(candidate_dir.resolve()),
        "files": files,
    }


def historical_backup_entity_roots(mac_root: Path, xfer_root: Path) -> dict[str, Path]:
    shared = mac_root / "VPO-1216"
    return {
        "VPO-083": xfer_root / "VPO-083 Romanswiller Stiehr-Mockers" / "extracted",
        **{entity_id: shared for entity_id in ("VPO-085", "VPO-086", "VPO-087", "VPO-088", "VPO-089", "VPO-090", "VPO-091", "VPO-092")},
        "VPO-187": xfer_root / "VPO-187 Veendam Kaat Tijhuis" / "extracted",
    }


def run_command(command: list[str], working_directory: Path) -> None:
    result = subprocess.run(command, cwd=working_directory, check=False)
    if result.returncode != 0:
        raise ReproductionError(f"Command failed with status {result.returncode}: {' '.join(command)}")


def reproduce_from_backup(arguments: argparse.Namespace) -> dict[str, Any]:
    project_root = Path(__file__).resolve().parents[2]
    output = arguments.output.resolve()
    output.mkdir(parents=True, exist_ok=True)
    remapped_inventory_path = output / "remapped-inventory.csv"
    remap_report = remap_inventory(
        arguments.inventory,
        remapped_inventory_path,
        [
            (arguments.historical_mac_prefix, str(arguments.mac_root.resolve())),
            (arguments.historical_xfer_prefix, str(arguments.xfer_root.resolve())),
        ],
    )
    write_json(output / "inventory-remap-report.json", remap_report)
    if remap_report["summary"]["historicallyExpectedPresentMissingPathCount"]:
        raise ReproductionError("Backup is missing one or more inventory paths that were historically present")

    lock = load_json(arguments.lock)
    if lock.get("contractVersion") != LOCK_CONTRACT:
        raise ReproductionError("Unsupported acquisition lock contract")
    verification = verify_acquisition(
        lock,
        output / "not-used",
        historical_backup_entity_roots(arguments.mac_root, arguments.xfer_root),
    )
    write_json(output / "backup-analysis-input-verification.json", verification)
    if not verification["equivalent"]:
        raise ReproductionError("Backup is a dataset variant; raw-audio analysis was not started")

    candidate_corpus = output / "retrieved-local-research-corpus.json"
    run_command(
        [
            "swift", "run", "-c", "release", "OrgRecDatasetTool", "retrieved-corpus-build",
            str(remapped_inventory_path), str(arguments.catalog.resolve()), str(candidate_corpus),
            "--include-unreviewed-rights", "--max-pipes", "9", "--min-pipes", "3",
        ],
        project_root,
    )
    corpus_comparison = compare_corpora(arguments.reference_corpus, candidate_corpus)
    write_json(output / "feature-corpus-comparison.json", corpus_comparison)
    if not corpus_comparison["equivalent"]:
        raise ReproductionError("Rebuilt feature corpus is a corpus variant; statistical analysis was not started")

    study_dir = output / "Study"
    results_dir = output / "Results"
    run_command(
        ["swift", "run", "-c", "release", "OrgRecDatasetTool", "comparative-study-export", str(candidate_corpus), str(study_dir)],
        project_root,
    )
    run_command(
        [sys.executable, str(project_root / "Research/ComparativeStopTimbre/analyze.py"), str(study_dir / "comparative-corpus.json"), str(results_dir)],
        project_root,
    )
    result_comparison = compare_results(arguments.reference_results, results_dir)
    write_json(output / "result-comparison.json", result_comparison)
    report = {
        "contractVersion": "orgrec-vpo-backup-reproduction-run/1",
        "generatedAt": utc_now(),
        "status": "exact scientific reproduction" if result_comparison["equivalent"] else "result variant",
        "analysisInputStatus": verification["status"],
        "featureCorpusStatus": corpus_comparison["status"],
        "resultStatus": result_comparison["status"],
        "output": str(output),
        "downloadedBytes": 0,
    }
    write_json(output / "reproduction-run.json", report)
    return report


def csv_by_id(path: Path) -> dict[str, dict[str, str]]:
    with path.open(encoding="utf-8-sig", newline="") as handle:
        return {row["entity_id"]: row for row in csv.DictReader(handle)}


def build_lock(
    corpus_path: Path,
    inventory_path: Path,
    catalog_path: Path,
    routes_path: Path,
) -> dict[str, Any]:
    corpus = load_json(corpus_path)
    if corpus.get("contractVersion") != "orgrec-retrieved-timbre-corpus/1":
        raise ReproductionError("Unsupported retrieved-corpus contract")
    inventory_hash = sha256_file(inventory_path)
    catalog_hash = sha256_file(catalog_path)
    if inventory_hash != corpus.get("inventorySHA256"):
        raise ReproductionError("Inventory SHA-256 does not match the frozen corpus")
    if catalog_hash != corpus.get("catalogSHA256"):
        raise ReproductionError("Catalog SHA-256 does not match the frozen corpus")

    inventory = csv_by_id(inventory_path)
    catalog = csv_by_id(catalog_path)
    routes_document = load_json(routes_path)
    if routes_document.get("contractVersion") != "orgrec-vpo-source-routes/1":
        raise ReproductionError("Unsupported source-route contract")
    routes = routes_document.get("routes", {})

    ranks_by_entity: dict[str, list[dict[str, Any]]] = {}
    for rank in corpus.get("ranks", []):
        ranks_by_entity.setdefault(rank["instrumentID"], []).append(rank)
    summaries = {item["entityID"]: item for item in corpus.get("instruments", [])}
    contributing_ids = sorted(ranks_by_entity)
    entities: list[dict[str, Any]] = []
    for entity_id in contributing_ids:
        if entity_id not in summaries:
            raise ReproductionError(f"Missing instrument summary for {entity_id}")
        if entity_id not in routes:
            raise ReproductionError(f"Missing acquisition route for {entity_id}")
        ranks = ranks_by_entity[entity_id]
        hashes = sorted(
            {
                observation["sourceAudioSHA256"]
                for rank in ranks
                for observation in rank.get("observations", [])
            }
        )
        if not hashes or any(len(value) != 64 for value in hashes):
            raise ReproductionError(f"Invalid or empty audio hash set for {entity_id}")
        summary = summaries[entity_id]
        route = routes[entity_id]
        inv = inventory.get(entity_id, {})
        cat = catalog.get(entity_id, {})
        entities.append(
            {
                "entityID": entity_id,
                "entityName": summary["instrumentName"],
                "producer": summary["producer"],
                "licenseClass": summary["licenseClass"],
                "accessModel": cat.get("access_model", inv.get("access_model", "")),
                "sourcePageURL": route["sourcePageURL"],
                "catalogSourceURL": summary["sourceURL"],
                "downloads": route["downloads"],
                "routeNote": route.get("note"),
                "definitionSHA256": summary["sourceDefinitionSHA256"],
                "requiredAudioSHA256": hashes,
                "rankCount": len(ranks),
                "observationCount": sum(len(rank.get("observations", [])) for rank in ranks),
                "uniqueAudioFileCount": len(hashes),
            }
        )

    total_download_bytes = sum(
        int(download["expectedBytes"])
        for entity in entities
        for download in entity["downloads"]
    )
    unique_hashes = {
        value for entity in entities for value in entity["requiredAudioSHA256"]
    }
    return {
        "contractVersion": LOCK_CONTRACT,
        "scope": "The ten VPO entities that contributed at least one rank to the frozen comparative stop-timbre analysis.",
        "equivalenceDefinition": {
            "statusName": "analysis-input equivalent",
            "requirements": [
                "Every contributing entity is present.",
                "The selected GrandOrgue definition SHA-256 matches.",
                "Every distinct source-audio SHA-256 used by a frozen pipe observation is present under the same entity.",
                "Downloads are extracted without changing their package-relative directory structure.",
            ],
            "variantRule": "If any required entity, definition digest, or analyzed audio digest is missing or changed, the acquisition is a dataset variant and is not equivalent to the referenced analysis input.",
            "wholeCollectionBoundary": "The former 591 GB discovery collection has no retained collection-wide per-file or package checksum manifest. Its byte-for-byte equivalence is therefore not assessable from surviving records; this lock covers the analyzed subset only.",
        },
        "frozenCorpus": {
            "fileName": corpus_path.name,
            "sha256": sha256_file(corpus_path),
            "contractVersion": corpus["contractVersion"],
            "generatedAt": corpus.get("generatedAt"),
            "inventorySHA256": inventory_hash,
            "catalogSHA256": catalog_hash,
        },
        "sourceRoutes": {
            "contractVersion": routes_document["contractVersion"],
            "reviewedAt": routes_document.get("reviewedAt"),
            "sha256": sha256_file(routes_path),
        },
        "counts": {
            "entityCount": len(entities),
            "rankCount": sum(entity["rankCount"] for entity in entities),
            "pipeObservationCount": sum(entity["observationCount"] for entity in entities),
            "entityScopedUniqueAudioFileCount": sum(entity["uniqueAudioFileCount"] for entity in entities),
            "globallyUniqueAudioDigestCount": len(unique_hashes),
            "expectedCompressedDownloadBytes": total_download_bytes,
        },
        "entities": entities,
    }


def request_head(url: str, timeout: float) -> dict[str, Any]:
    started = time.monotonic()
    request = Request(url, method="HEAD", headers={"User-Agent": USER_AGENT})
    try:
        with urlopen(request, timeout=timeout) as response:
            return {
                "available": 200 <= response.status < 400,
                "httpStatus": response.status,
                "finalURL": response.geturl(),
                "contentLength": int(response.headers["Content-Length"])
                if response.headers.get("Content-Length", "").isdigit()
                else None,
                "contentType": response.headers.get("Content-Type"),
                "etag": response.headers.get("ETag"),
                "lastModified": response.headers.get("Last-Modified"),
                "elapsedSeconds": round(time.monotonic() - started, 3),
            }
    except HTTPError as error:
        return {
            "available": False,
            "httpStatus": error.code,
            "error": str(error),
            "elapsedSeconds": round(time.monotonic() - started, 3),
        }
    except (URLError, TimeoutError, OSError) as error:
        return {
            "available": False,
            "error": str(error),
            "elapsedSeconds": round(time.monotonic() - started, 3),
        }


def audit_routes(lock: dict[str, Any], timeout: float = 30.0) -> dict[str, Any]:
    records = []
    for entity in lock["entities"]:
        for download in entity["downloads"]:
            result = request_head(download["url"], timeout)
            expected = int(download["expectedBytes"])
            observed = result.get("contentLength")
            result.update(
                {
                    "entityID": entity["entityID"],
                    "url": download["url"],
                    "expectedBytes": expected,
                    "expectedBytesBasis": download.get("expectedBytesBasis"),
                    "sizeMatches": observed == expected if observed is not None else None,
                    "byteIdentityProven": False,
                }
            )
            records.append(result)
    available = sum(bool(record["available"]) for record in records)
    size_matches = sum(record.get("sizeMatches") is True for record in records)
    return {
        "contractVersion": AUDIT_CONTRACT,
        "generatedAt": utc_now(),
        "lockSHA256": canonical_json_hash(lock),
        "summary": {
            "routeCount": len(records),
            "availableCount": available,
            "unavailableCount": len(records) - available,
            "matchingContentLengthCount": size_matches,
            "allRoutesAvailable": available == len(records),
            "allAvailableSizesMatch": size_matches == len(records),
            "interpretation": "Availability and byte length are discovery checks only. Exact equivalence is established only by verify against the frozen internal SHA-256 values.",
        },
        "routes": records,
    }


def selected_entities(lock: dict[str, Any], entity_ids: list[str] | None) -> list[dict[str, Any]]:
    entities = lock["entities"]
    if not entity_ids:
        return entities
    requested = set(entity_ids)
    known = {entity["entityID"] for entity in entities}
    unknown = sorted(requested - known)
    if unknown:
        raise ReproductionError(f"Unknown entity IDs: {', '.join(unknown)}")
    return [entity for entity in entities if entity["entityID"] in requested]


def download_file(specification: dict[str, Any], target: Path, timeout: float) -> dict[str, Any]:
    expected_bytes = int(specification["expectedBytes"])
    expected_hash = specification.get("expectedSHA256")
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists():
        size = target.stat().st_size
        digest = sha256_file(target) if expected_hash and size == expected_bytes else None
        if size == expected_bytes and (not expected_hash or digest == expected_hash):
            return {"status": "already-present", "path": str(target), "bytes": size, "sha256": digest}
        raise ReproductionError(
            f"Existing download does not match its lock and was preserved: {target}"
        )

    partial = target.with_name(target.name + ".part")
    offset = partial.stat().st_size if partial.exists() else 0
    headers = {"User-Agent": USER_AGENT}
    if offset:
        headers["Range"] = f"bytes={offset}-"
    request = Request(specification["url"], headers=headers)
    with urlopen(request, timeout=timeout) as response:
        append = offset > 0 and response.status == 206
        mode = "ab" if append else "wb"
        if not append:
            offset = 0
        with partial.open(mode) as handle:
            while chunk := response.read(8 * 1024 * 1024):
                handle.write(chunk)
    actual_bytes = partial.stat().st_size
    if actual_bytes != expected_bytes:
        raise ReproductionError(
            f"Incomplete or changed download for {target.name}: {actual_bytes} bytes, expected {expected_bytes}; resumable .part retained"
        )
    digest = sha256_file(partial) if expected_hash else None
    if expected_hash and digest != expected_hash:
        raise ReproductionError(
            f"SHA-256 mismatch for {target.name}; downloaded .part retained as variant evidence"
        )
    os.replace(partial, target)
    return {"status": "downloaded", "path": str(target), "bytes": actual_bytes, "sha256": digest}


def safe_archive_member(name: str) -> bool:
    normalized = name.replace("\\", "/")
    path = PurePosixPath(normalized)
    return not path.is_absolute() and ".." not in path.parts


def extract_zip(archive: Path, destination: Path) -> None:
    with zipfile.ZipFile(archive) as handle:
        bad = [name for name in handle.namelist() if not safe_archive_member(name)]
        if bad:
            raise ReproductionError(f"Unsafe archive paths in {archive.name}: {bad[:3]}")
        failed = handle.testzip()
        if failed:
            raise ReproductionError(f"ZIP integrity failure in {archive.name}: {failed}")
        handle.extractall(destination)


def extract_external(archive: Path, destination: Path) -> None:
    extractor = shutil.which("bsdtar") or shutil.which("unar")
    if not extractor:
        raise ReproductionError("RAR/7z extraction requires bsdtar or unar")
    if Path(extractor).name == "bsdtar":
        listing = subprocess.run(
            [extractor, "-tf", str(archive)], capture_output=True, text=True, check=False
        )
        if listing.returncode != 0:
            raise ReproductionError(f"Archive listing failed: {listing.stderr[-800:]}")
        bad = [name for name in listing.stdout.splitlines() if not safe_archive_member(name)]
        if bad:
            raise ReproductionError(f"Unsafe archive paths in {archive.name}: {bad[:3]}")
        command = [extractor, "-xf", str(archive), "-C", str(destination)]
    else:
        command = [extractor, "-quiet", "-force-overwrite", "-output-directory", str(destination), str(archive)]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode != 0:
        raise ReproductionError(f"Archive extraction failed: {(result.stdout + result.stderr)[-1200:]}")


def extract_archive(archive: Path, archive_format: str, destination: Path) -> dict[str, Any]:
    archive_hash = sha256_file(archive)
    marker = destination / ".orgrec-extraction.json"
    if destination.exists():
        if marker.exists() and load_json(marker).get("archiveSHA256") == archive_hash:
            return {"status": "already-extracted", "path": str(destination), "archiveSHA256": archive_hash}
        raise ReproductionError(
            f"Extraction destination exists without a matching marker and was preserved: {destination}"
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=destination.name + ".tmp-", dir=destination.parent))
    try:
        if archive_format == "zip":
            extract_zip(archive, temporary)
        elif archive_format in {"rar", "7z"}:
            extract_external(archive, temporary)
        else:
            raise ReproductionError(f"Unsupported archive format: {archive_format}")
        if not any(path.is_file() for path in temporary.rglob("*")):
            raise ReproductionError(f"Archive extracted no files: {archive.name}")
        symlinks = [
            str(path.relative_to(temporary))
            for path in temporary.rglob("*")
            if path.is_symlink()
        ]
        if symlinks:
            raise ReproductionError(f"Archive contains unsupported symbolic links: {symlinks[:3]}")
        write_json(
            temporary / ".orgrec-extraction.json",
            {
                "contractVersion": "orgrec-vpo-preserved-extraction/1",
                "archive": archive.name,
                "archiveSHA256": archive_hash,
                "extractedAt": utc_now(),
            },
        )
        os.replace(temporary, destination)
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise
    return {"status": "extracted", "path": str(destination), "archiveSHA256": archive_hash}


def download_entities(
    lock: dict[str, Any],
    destination: Path,
    entity_ids: list[str] | None,
    extract: bool,
    timeout: float,
) -> dict[str, Any]:
    records = []
    for entity in selected_entities(lock, entity_ids):
        entity_root = destination / entity["entityID"]
        for specification in entity["downloads"]:
            archive = entity_root / "downloads" / specification["filename"]
            download_record = download_file(specification, archive, timeout)
            record = {"entityID": entity["entityID"], "download": download_record}
            if extract:
                record["extraction"] = extract_archive(
                    archive,
                    specification["archiveFormat"],
                    entity_root / "extracted" / Path(specification["filename"]).stem,
                )
            records.append(record)
    report = {
        "contractVersion": "orgrec-vpo-analysis-acquisition-run/1",
        "generatedAt": utc_now(),
        "destination": str(destination.resolve()),
        "lockSHA256": canonical_json_hash(lock),
        "records": records,
    }
    write_json(destination / "acquisition-report.json", report)
    return report


def digest_index(root: Path) -> dict[str, Any]:
    audio: dict[str, str] = {}
    definitions: dict[str, list[str]] = {}
    scanned_files = 0
    scanned_bytes = 0
    if not root.exists():
        return {
            "audio": audio,
            "definitions": definitions,
            "scannedCandidateFileCount": scanned_files,
            "scannedCandidateBytes": scanned_bytes,
        }
    for path in root.rglob("*"):
        if not path.is_file() or path.name.startswith("._"):
            continue
        suffix = path.suffix.lower()
        if suffix in HASH_EXTENSIONS:
            scanned_files += 1
            scanned_bytes += path.stat().st_size
            digest = sha256_file(path)
            display = str(path.relative_to(root))
            if suffix in AUDIO_EXTENSIONS:
                audio.setdefault(digest, display)
            else:
                definitions.setdefault(digest, []).append(display)
        elif suffix in {".orgue", ".zip"} and zipfile.is_zipfile(path):
            managed_marker = root / "extracted" / path.stem / ".orgrec-extraction.json"
            if managed_marker.exists():
                continue
            with zipfile.ZipFile(path) as archive:
                for info in archive.infolist():
                    member_suffix = PurePosixPath(info.filename).suffix.lower()
                    if info.is_dir() or member_suffix not in HASH_EXTENSIONS:
                        continue
                    if not safe_archive_member(info.filename):
                        raise ReproductionError(f"Unsafe archive path in {path}: {info.filename}")
                    scanned_files += 1
                    scanned_bytes += info.file_size
                    with archive.open(info) as handle:
                        digest = sha256_stream(handle)
                    display = f"{path.relative_to(root)}!/{info.filename}"
                    if member_suffix in AUDIO_EXTENSIONS:
                        audio.setdefault(digest, display)
                    else:
                        definitions.setdefault(digest, []).append(display)
    return {
        "audio": audio,
        "definitions": definitions,
        "scannedCandidateFileCount": scanned_files,
        "scannedCandidateBytes": scanned_bytes,
    }


def verify_acquisition(
    lock: dict[str, Any],
    destination: Path,
    entity_root_overrides: dict[str, Path] | None = None,
) -> dict[str, Any]:
    entity_reports = []
    total_required_audio = 0
    total_found_audio = 0
    matched_definitions = 0
    overrides = entity_root_overrides or {}
    indexes: dict[Path, dict[str, Any]] = {}
    for entity in lock["entities"]:
        entity_root = overrides.get(entity["entityID"], destination / entity["entityID"])
        key = entity_root.resolve()
        if key not in indexes:
            indexes[key] = digest_index(entity_root)
        index = indexes[key]
        required_audio = set(entity["requiredAudioSHA256"])
        required_definition = entity["definitionSHA256"]
        total_required_audio += len(required_audio)
        found_audio = {
            digest: index["audio"][digest]
            for digest in required_audio
            if digest in index["audio"]
        }
        definition_matches = index["definitions"].get(required_definition, [])
        missing_audio = sorted(required_audio - set(found_audio))
        total_found_audio += len(found_audio)
        if definition_matches:
            matched_definitions += 1
        equivalent = not missing_audio and bool(definition_matches)
        entity_reports.append(
            {
                "entityID": entity["entityID"],
                "status": "equivalent" if equivalent else "variant",
                "entityRoot": str(entity_root),
                "requiredAudioFileCount": len(required_audio),
                "matchedAudioFileCount": len(found_audio),
                "missingAudioSHA256": missing_audio,
                "definitionSHA256": required_definition,
                "definitionMatches": definition_matches,
                "scannedCandidateFileCount": index["scannedCandidateFileCount"],
                "scannedCandidateBytes": index["scannedCandidateBytes"],
            }
        )
    equivalent = all(report["status"] == "equivalent" for report in entity_reports)
    return {
        "contractVersion": VERIFY_CONTRACT,
        "generatedAt": utc_now(),
        "lockSHA256": canonical_json_hash(lock),
        "destination": str(destination.resolve()),
        "status": "analysis-input equivalent" if equivalent else "dataset variant",
        "equivalent": equivalent,
        "summary": {
            "requiredEntityCount": len(entity_reports),
            "equivalentEntityCount": sum(report["status"] == "equivalent" for report in entity_reports),
            "requiredDefinitionCount": len(entity_reports),
            "matchedDefinitionCount": matched_definitions,
            "requiredEntityScopedAudioFileCount": total_required_audio,
            "matchedEntityScopedAudioFileCount": total_found_audio,
            "audioCompletenessFraction": total_found_audio / total_required_audio if total_required_audio else 0,
            "wholeFormerCollectionEquivalence": "not assessable",
        },
        "entities": entity_reports,
    }


def print_audit(report: dict[str, Any]) -> None:
    summary = report["summary"]
    print(
        f"routes={summary['routeCount']} available={summary['availableCount']} "
        f"size_matches={summary['matchingContentLengthCount']}"
    )
    for route in report["routes"]:
        status = "available" if route["available"] else "unavailable"
        size = "size-match" if route.get("sizeMatches") is True else "size-unverified-or-changed"
        print(f"{route['entityID']} {status} {size} {route['url']}")


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(
        description=__doc__,
        epilog=(
            "Scientific protocol: Docs/COMPARATIVE_STOP_TIMBRE_STUDY.md. "
            "Dataset protocol: Docs/VPO_DATASET_REPRODUCIBILITY.md."
        ),
    )
    commands = result.add_subparsers(dest="command", required=True)
    project_root = Path(__file__).resolve().parents[2]
    frozen_inputs = project_root / "Artifacts/ComparativeStopTimbre/Inputs"
    frozen_artifacts = project_root / "Artifacts/ComparativeStopTimbre"

    lock = commands.add_parser("lock", help="Generate the immutable analyzed-input lock")
    lock.add_argument("--corpus", type=Path, required=True)
    lock.add_argument("--inventory", type=Path, required=True)
    lock.add_argument("--catalog", type=Path, required=True)
    lock.add_argument("--routes", type=Path, required=True)
    lock.add_argument("--output", type=Path, required=True)

    audit = commands.add_parser("audit", help="Check current source-route availability without downloading payloads")
    audit.add_argument("--lock", type=Path, required=True)
    audit.add_argument("--report", type=Path)
    audit.add_argument("--timeout", type=float, default=30.0)

    download = commands.add_parser("download", help="Download, retain, and optionally extract the locked source packages")
    download.add_argument("--lock", type=Path, required=True)
    download.add_argument("--destination", type=Path, required=True)
    download.add_argument("--entity", action="append", dest="entities")
    download.add_argument("--no-extract", action="store_true")
    download.add_argument("--timeout", type=float, default=120.0)
    download.add_argument(
        "--accept-source-terms",
        action="store_true",
        help="Confirm that the operator reviewed current source terms and is authorized to download",
    )

    verify = commands.add_parser("verify", help="Hash extracted files and classify the acquisition as equivalent or variant")
    verify.add_argument("--lock", type=Path, required=True)
    verify.add_argument("--destination", type=Path, required=True)
    verify.add_argument("--report", type=Path)
    verify.add_argument(
        "--entity-root",
        action="append",
        default=[],
        metavar="ENTITY_ID=PATH",
        help="Override an entity's scan root; repeatable and useful for the historical backup layout",
    )

    remap = commands.add_parser("remap-inventory", help="Rewrite historical volume prefixes for a mounted backup")
    remap.add_argument("--inventory", type=Path, required=True)
    remap.add_argument("--output", type=Path, required=True)
    remap.add_argument("--report", type=Path)
    remap.add_argument(
        "--root-map",
        action="append",
        required=True,
        metavar="OLD=NEW",
        help="Map an exact old filesystem root to its mounted replacement; repeatable",
    )

    compare_corpus = commands.add_parser("compare-corpus", help="Compare rebuilt and frozen scientific corpus payloads")
    compare_corpus.add_argument("--reference", type=Path, required=True)
    compare_corpus.add_argument("--candidate", type=Path, required=True)
    compare_corpus.add_argument("--report", type=Path, required=True)

    compare_result = commands.add_parser("compare-results", help="Compare rebuilt and frozen statistical tables")
    compare_result.add_argument("--reference", type=Path, required=True)
    compare_result.add_argument("--candidate", type=Path, required=True)
    compare_result.add_argument("--report", type=Path, required=True)

    reproduce = commands.add_parser("reproduce-backup", help="Verify a historical backup and reproduce the full analysis without downloading")
    reproduce.add_argument("--mac-root", type=Path, required=True, help="Mounted replacement for the first historical dataset root")
    reproduce.add_argument("--xfer-root", type=Path, required=True, help="Mounted replacement for the second historical dataset root")
    reproduce.add_argument("--historical-mac-prefix", required=True, help="Exact first path prefix recorded in the frozen inventory")
    reproduce.add_argument("--historical-xfer-prefix", required=True, help="Exact second path prefix recorded in the frozen inventory")
    reproduce.add_argument("--inventory", type=Path, default=frozen_inputs / "downloaded_instrument_inventory.csv")
    reproduce.add_argument("--catalog", type=Path, default=frozen_inputs / "virtual_pipe_organ_datasets_and_instruments_2026-08-17_expanded_3600.csv")
    reproduce.add_argument("--lock", type=Path, default=frozen_artifacts / "vpo-analysis-acquisition-lock.json")
    reproduce.add_argument("--reference-corpus", type=Path, default=frozen_artifacts / "retrieved-local-research-corpus.json")
    reproduce.add_argument("--reference-results", type=Path, default=frozen_artifacts / "Results")
    reproduce.add_argument("--output", type=Path, required=True)
    return result


def parse_entity_roots(values: list[str]) -> dict[str, Path]:
    result: dict[str, Path] = {}
    for value in values:
        if "=" not in value:
            raise ReproductionError(f"Invalid --entity-root value: {value}")
        entity_id, raw_path = value.split("=", 1)
        entity_id = entity_id.strip()
        if not entity_id or not raw_path:
            raise ReproductionError(f"Invalid --entity-root value: {value}")
        if entity_id in result:
            raise ReproductionError(f"Duplicate --entity-root for {entity_id}")
        result[entity_id] = Path(raw_path)
    return result


def main(argv: list[str] | None = None) -> int:
    arguments = parser().parse_args(argv)
    try:
        if arguments.command == "lock":
            document = build_lock(arguments.corpus, arguments.inventory, arguments.catalog, arguments.routes)
            write_json(arguments.output, document)
            print(json.dumps({"output": str(arguments.output), "sha256": sha256_file(arguments.output), "counts": document["counts"]}, indent=2))
            return 0
        if arguments.command == "remap-inventory":
            report = remap_inventory(arguments.inventory, arguments.output, parse_root_maps(arguments.root_map))
            if arguments.report:
                write_json(arguments.report, report)
            print(json.dumps({"output": str(arguments.output), "summary": report["summary"]}, indent=2))
            return 0 if report["summary"]["historicallyExpectedPresentMissingPathCount"] == 0 else 2
        if arguments.command == "compare-corpus":
            report = compare_corpora(arguments.reference, arguments.candidate)
            write_json(arguments.report, report)
            print(json.dumps({"status": report["status"], "report": str(arguments.report)}, indent=2))
            return 0 if report["equivalent"] else 2
        if arguments.command == "compare-results":
            report = compare_results(arguments.reference, arguments.candidate)
            write_json(arguments.report, report)
            print(json.dumps({"status": report["status"], "report": str(arguments.report)}, indent=2))
            return 0 if report["equivalent"] else 2
        if arguments.command == "reproduce-backup":
            report = reproduce_from_backup(arguments)
            print(json.dumps(report, indent=2))
            return 0 if report["status"] == "exact scientific reproduction" else 2
        lock = load_json(arguments.lock)
        if lock.get("contractVersion") != LOCK_CONTRACT:
            raise ReproductionError("Unsupported acquisition lock contract")
        if arguments.command == "audit":
            report = audit_routes(lock, arguments.timeout)
            if arguments.report:
                write_json(arguments.report, report)
            print_audit(report)
            return 0 if report["summary"]["allRoutesAvailable"] else 2
        if arguments.command == "download":
            if not arguments.accept_source_terms:
                raise ReproductionError(
                    "Downloading requires --accept-source-terms after reviewing current licences and access terms"
                )
            report = download_entities(
                lock,
                arguments.destination,
                arguments.entities,
                not arguments.no_extract,
                arguments.timeout,
            )
            print(json.dumps({"destination": report["destination"], "recordCount": len(report["records"])}, indent=2))
            return 0
        if arguments.command == "verify":
            overrides = parse_entity_roots(arguments.entity_root)
            known = {entity["entityID"] for entity in lock["entities"]}
            unknown = sorted(set(overrides) - known)
            if unknown:
                raise ReproductionError(f"Unknown entity-root IDs: {', '.join(unknown)}")
            report = verify_acquisition(lock, arguments.destination, overrides)
            output = arguments.report or arguments.destination / "verification-report.json"
            write_json(output, report)
            print(json.dumps({"status": report["status"], "summary": report["summary"], "report": str(output)}, indent=2))
            return 0 if report["equivalent"] else 2
        raise ReproductionError(f"Unknown command: {arguments.command}")
    except (ReproductionError, OSError, ValueError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
